# This rule is not used by the project s4t-rbac-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over s4t.s4t.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: s4t-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-admin-role
rules:
- apiGroups:
  - s4t.s4t.io
  resources:
  - projects
  verbs:
  - '*'
- apiGroups:
  - s4t.s4t.io
  resources:
  - projects/status
  verbs:
  - get
