apiVersion: s4t.s4t.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: s4t-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  # TODO(user): Add fields here
